// Emits src/lib/tokens.css from scripts/ui-tokens.js. Run by the view generator.
import fs from 'fs';
import { TOKENS } from './ui-tokens.js';

const block = mode => Object.entries(TOKENS).map(([k, v]) => `  --pw-${k}: ${v[mode]};`).join('\n');
fs.mkdirSync('src/lib', { recursive: true });
fs.writeFileSync('src/lib/tokens.css', `/* GENERATED by scripts/build-tokens.mjs from scripts/ui-tokens.js — do not edit. */

/* Light is the default. */
:root {
  color-scheme: light;
${block('light')}
}

/* Dark: the system preference unless the user picked light … */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    color-scheme: dark;
${block('dark')}
  }
}

/* … or an explicit choice, which wins in both directions. */
:root[data-theme="dark"] {
  color-scheme: dark;
${block('dark')}
}
`);
console.log('src/lib/tokens.css', Object.keys(TOKENS).length, 'tokens');
