import fs from 'fs';
import path from 'path';

/**
 * Emits the service worker with the built app shell stamped into it.
 *
 * The precache list has to name the hashed bundles, which only exist after the
 * build, so the worker is generated here rather than kept in `public/`. Bumping the
 * asset hashes changes the cache name, which is what retires the old caches.
 */
export default function serviceWorker({ extraPrecache = [] } = {}) {
  let outDir = 'dist';
  return {
    name: 'pinwheel-service-worker',
    apply: 'build',
    configResolved(config) { outDir = config.build.outDir; },
    closeBundle() {
      const root = path.resolve(outDir);
      const walk = dir => fs.readdirSync(dir, { withFileTypes: true }).flatMap(e => {
        const full = path.join(dir, e.name);
        return e.isDirectory() ? walk(full) : [path.relative(root, full).split(path.sep).join('/')];
      });
      const shell = walk(root)
        .filter(f => !f.endsWith('.map') && f !== 'sw.js')
        // The spec page and the icons are small and worth having offline; user assets
        // never touch this cache because they never leave the document.
        .map(f => './' + f);

      const version = 'pinwheel-' + hash(shell.join('|'));
      const sw = `// GENERATED by scripts/sw-plugin.js at build time — do not edit.
// Precaches the app shell so the studio opens offline (spec §12). Nothing the user
// makes is stored here; documents live in the page and in .pinwheel files.
const CACHE = ${JSON.stringify(version)};
const SHELL = ${JSON.stringify([...shell, ...extraPrecache], null, 2)};

self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE).then(c => c.addAll(SHELL)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k.startsWith('pinwheel-') && k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', event => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return; // CDN and font hosts do their own caching

  // Navigations fall back to the cached shell so a reload works offline.
  if (req.mode === 'navigate') {
    event.respondWith(
      fetch(req).catch(() => caches.match('./index.html', { ignoreSearch: true }).then(r => r || Response.error()))
    );
    return;
  }

  // Everything else is content-hashed, so cache-first is safe and fast.
  event.respondWith(
    caches.match(req, { ignoreSearch: true }).then(hit => hit || fetch(req).then(res => {
      if (res.ok && res.type === 'basic') {
        const copy = res.clone();
        caches.open(CACHE).then(c => c.put(req, copy));
      }
      return res;
    }))
  );
});
`;
      fs.writeFileSync(path.join(root, 'sw.js'), sw);

      console.log(`  service worker: ${shell.length} shell files, cache ${version}`);
    },
  };
}

function hash(s) {
  let h = 5381;
  for (let i = 0; i < s.length; i++) h = ((h * 33) ^ s.charCodeAt(i)) >>> 0;
  return h.toString(36);
}
