// GENERATED by scripts/dc-to-jsx.mjs from the design prototype — see docs/PORTING.md.
// Presentation only: every value comes from Studio#renderVals().
import { Fragment } from 'react';
import { sty, toArray } from './lib/style.js';

export default function StudioView(v) {
  return (
    <>
    <div style={{ height: "100vh", display: "flex", flexDirection: "column", background: "#F4F2EE", fontFamily: "'Source Sans 3', system-ui, sans-serif", color: "#24211D", fontSize: "14px", overflow: "hidden" }}>
      {v.loading ? (
        <>
          <div style={{ flex: "1", display: "flex", alignItems: "center", justifyContent: "center", flexDirection: "column", gap: "14px" }}>
            <div style={{ display: "grid", gridTemplateColumns: "18px 18px", gap: "3px" }}>
              <div style={{ width: "18px", height: "18px", background: "#E8674A", borderRadius: "18px 0 0 0" }} />
              <div style={{ width: "18px", height: "18px", background: "#24211D", borderRadius: "0 18px 0 0" }} />
              <div style={{ width: "18px", height: "18px", background: "#24211D", borderRadius: "0 0 0 18px" }} />
              <div style={{ width: "18px", height: "18px", background: "#E8674A", borderRadius: "0 0 18px 0" }} />
            </div>
            <div style={{ fontSize: "15px", color: "#6E675E" }}>
              {v.loadingText}
            </div>
          </div>
        </>
      ) : null}
      {v.isHome ? (
        <>
          <div style={{ flex: "1", overflow: "auto" }}>
            <header style={{ display: "flex", alignItems: "center", gap: "18px", padding: "12px 32px", borderBottom: "1px solid #E6E1D9", background: "#FBFAF8", position: "sticky", top: "0", zIndex: "10" }}>
              <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
                <div style={{ display: "grid", gridTemplateColumns: "11px 11px", gap: "2px" }}>
                  <div style={{ width: "11px", height: "11px", background: "#E8674A", borderRadius: "11px 0 0 0" }} />
                  <div style={{ width: "11px", height: "11px", background: "#24211D", borderRadius: "0 11px 0 0" }} />
                  <div style={{ width: "11px", height: "11px", background: "#24211D", borderRadius: "0 0 0 11px" }} />
                  <div style={{ width: "11px", height: "11px", background: "#E8674A", borderRadius: "0 0 11px 0" }} />
                </div>
                <div style={{ fontWeight: "700", fontSize: "17px", letterSpacing: "-0.01em" }}>
                  Pinwheel Studio
                </div>
              </div>
              <div style={{ flex: "1" }} />
              <a href="spec.html" style={{ fontSize: "14px", fontWeight: "600", color: "#6E675E" }}>
                Spec & file format
              </a>
              <button onClick={v.openFile} style={{ height: "34px", padding: "0 14px", borderRadius: "8px", border: "1px solid #E0DBD2", background: "#FFFFFF", fontWeight: "600", fontSize: "14px", cursor: "pointer", color: "#24211D" }} className="pw-h1">
                Open .pinwheel file
              </button>
            </header>
            <main style={{ maxWidth: "1360px", margin: "0 auto", padding: "40px 32px 96px", display: "flex", flexDirection: "column", gap: "36px" }}>
              <section style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
                <h1 style={{ margin: "0", fontSize: "40px", lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700", textWrap: "pretty" }}>
                  What are you making today?
                </h1>
                <div style={{ color: "#6E675E", fontSize: "16px" }}>
                  {v.statLine}
                </div>
                <div style={{ display: "flex", gap: "10px", alignItems: "center", maxWidth: "640px", background: "#FFFFFF", border: "1px solid #E0DBD2", borderRadius: "12px", padding: "0 14px", height: "48px" }}>
                  <div style={{ width: "14px", height: "14px", border: "2px solid #9A9389", borderRadius: "50%", flex: "none" }} />
                  <input value={v.galQ ?? ''} onChange={v.onGalQ} placeholder="Search templates — try “podcast”, “sale”, “wedding”, “thumbnail”" style={{ flex: "1", border: "none", outline: "none", fontSize: "16px", background: "transparent", minWidth: "0" }} />
                </div>
              </section>
              {v.hasAutosave ? (
                <>
                  <button onClick={v.resumeAutosave} style={{ alignSelf: "flex-start", display: "flex", alignItems: "center", gap: "12px", padding: "12px 16px", borderRadius: "12px", border: "1px solid #F3C9BC", background: "#FCEAE4", cursor: "pointer", color: "#24211D", fontSize: "15px" }} className="pw-h2">
                    <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "#E8674A" }} />
                    <span style={{ fontWeight: "700" }}>
                      Continue where you left off
                    </span>
                    <span style={{ color: "#6E675E" }}>
                      {v.autosaveName}
                    </span>
                  </button>
                </>
              ) : null}
              <section style={{ display: "flex", flexDirection: "column", gap: "14px" }}>
                <h2 style={{ margin: "0", fontSize: "18px", fontWeight: "700" }}>
                  Start blank
                </h2>
                <div style={{ display: "flex", flexWrap: "wrap", gap: "10px" }}>
                  {toArray(v.fmts).map((f, $index) => (
                    <Fragment key={$index}>
                      <button onClick={f.onClick} style={{ display: "flex", alignItems: "center", gap: "12px", padding: "10px 14px 10px 10px", borderRadius: "10px", border: "1px solid #E6E1D9", background: "#FFFFFF", cursor: "pointer", textAlign: "left", color: "#24211D" }} className="pw-h3">
                        <div style={{ width: "40px", height: "40px", display: "flex", alignItems: "center", justifyContent: "center", background: "#F4F2EE", borderRadius: "6px", flex: "none" }}>
                          <div style={sty(f.iconStyle)} />
                        </div>
                        <div style={{ display: "flex", flexDirection: "column" }}>
                          <span style={{ fontWeight: "600", fontSize: "14px" }}>
                            {f.name}
                          </span>
                          <span style={{ fontSize: "12px", color: "#8A837A", fontFamily: "'IBM Plex Mono', monospace" }}>
                            {f.dims}
                          </span>
                        </div>
                      </button>
                    </Fragment>
                  ))}
                  <div style={{ display: "flex", alignItems: "center", gap: "8px", padding: "10px 12px", borderRadius: "10px", border: "1px dashed #D8D3CA", background: "#FBFAF8" }}>
                    <span style={{ fontWeight: "600" }}>
                      Custom
                    </span>
                    <input type="number" value={v.customW ?? ''} onChange={v.onCustomW} style={{ width: "76px", height: "32px", border: "1px solid #E0DBD2", borderRadius: "6px", padding: "0 8px", fontFamily: "'IBM Plex Mono', monospace", fontSize: "13px" }} />
                    <span style={{ color: "#9A9389" }}>
                      ×
                    </span>
                    <input type="number" value={v.customH ?? ''} onChange={v.onCustomH} style={{ width: "76px", height: "32px", border: "1px solid #E0DBD2", borderRadius: "6px", padding: "0 8px", fontFamily: "'IBM Plex Mono', monospace", fontSize: "13px" }} />
                    <button onClick={v.createCustom} style={{ height: "32px", padding: "0 12px", borderRadius: "7px", border: "none", background: "#24211D", color: "#FFFFFF", fontWeight: "600", cursor: "pointer" }}>
                      Create
                    </button>
                  </div>
                </div>
              </section>
              <section style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
                <div style={{ display: "flex", alignItems: "baseline", gap: "12px", flexWrap: "wrap" }}>
                  <h2 style={{ margin: "0", fontSize: "18px", fontWeight: "700" }}>
                    Templates
                  </h2>
                  <span style={{ color: "#8A837A", fontSize: "14px" }}>
                    {v.galCount}
                  </span>
                </div>
                <div style={{ display: "flex", flexWrap: "wrap", gap: "8px" }}>
                  {toArray(v.galCats).map((c, $index) => (
                    <Fragment key={$index}>
                      <button onClick={c.onClick} style={sty(c.style)}>
                        {c.label}
                      </button>
                    </Fragment>
                  ))}
                </div>
                <div style={{ display: "flex", flexWrap: "wrap", gap: "28px 22px", alignItems: "flex-start" }}>
                  {toArray(v.galItems).map((g, $index) => (
                    <Fragment key={$index}>
                      <button onClick={g.onClick} title={g.title} style={sty(g.cardStyle)}>
                        <div style={sty(g.boxStyle)}>
                          {g.thumb}
                        </div>
                        <div style={{ fontSize: "14px", fontWeight: "600", color: "#24211D", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>
                          {g.name}
                        </div>
                        <div style={{ fontSize: "12px", color: "#8A837A", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>
                          {g.meta}
                        </div>
                      </button>
                    </Fragment>
                  ))}
                </div>
                {v.galEmpty ? (
                  <>
                    <div style={{ padding: "40px 0", color: "#6E675E", fontSize: "15px" }}>
                      No templates match that search. Try a topic like “coffee” or a format like “story”.
                    </div>
                  </>
                ) : null}
                {v.galHasMore ? (
                  <>
                    <button onClick={v.galMore} style={{ alignSelf: "center", height: "40px", padding: "0 22px", borderRadius: "10px", border: "1px solid #E0DBD2", background: "#FFFFFF", fontWeight: "600", fontSize: "14px", cursor: "pointer", color: "#24211D" }} className="pw-h1">
                      Show more templates
                    </button>
                  </>
                ) : null}
              </section>
            </main>
          </div>
        </>
      ) : null}
      {v.isEditor ? (
        <>
          <div style={{ flex: "1", display: "flex", flexDirection: "column", minHeight: "0" }}>
            <div style={{ height: "52px", flex: "none", display: "flex", alignItems: "center", gap: "8px", padding: "0 12px", background: "#FBFAF8", borderBottom: "1px solid #E6E1D9", position: "relative", zIndex: "20" }}>
              <button onClick={v.goHome} title="All templates" style={{ height: "34px", display: "flex", alignItems: "center", gap: "8px", padding: "0 10px", border: "none", background: "transparent", borderRadius: "8px", cursor: "pointer" }} className="pw-h4">
                <div style={{ display: "grid", gridTemplateColumns: "8px 8px", gap: "2px" }}>
                  <div style={{ width: "8px", height: "8px", background: "#E8674A", borderRadius: "8px 0 0 0" }} />
                  <div style={{ width: "8px", height: "8px", background: "#24211D", borderRadius: "0 8px 0 0" }} />
                  <div style={{ width: "8px", height: "8px", background: "#24211D", borderRadius: "0 0 0 8px" }} />
                  <div style={{ width: "8px", height: "8px", background: "#E8674A", borderRadius: "0 0 8px 0" }} />
                </div>
                <span style={{ fontWeight: "700", fontSize: "15px", color: "#24211D" }}>
                  Pinwheel
                </span>
              </button>
              <div style={{ width: "1px", height: "22px", background: "#E6E1D9" }} />
              <button onClick={v.toggleFile} style={{ height: "32px", padding: "0 10px", border: "none", background: "transparent", borderRadius: "7px", cursor: "pointer", fontWeight: "600", fontSize: "14px", color: "#24211D" }} className="pw-h4">
                File
              </button>
              <button onClick={v.toggleResize} style={{ height: "32px", padding: "0 10px", border: "none", background: "transparent", borderRadius: "7px", cursor: "pointer", fontWeight: "600", fontSize: "14px", color: "#24211D", display: "flex", gap: "8px", alignItems: "center" }} className="pw-h4">
                Resize 
                <span style={{ fontFamily: "'IBM Plex Mono', monospace", fontSize: "12px", color: "#8A837A", fontWeight: "400" }}>
                  {v.sizeLabel}
                </span>
              </button>
              <div style={{ width: "1px", height: "22px", background: "#E6E1D9" }} />
              <button onClick={v.undo} title="Undo (⌘Z)" style={sty(v.undoStyle)}>
                ↩
              </button>
              <button onClick={v.redo} title="Redo (⇧⌘Z)" style={sty(v.redoStyle)}>
                ↪
              </button>
              <div style={{ flex: "1", display: "flex", justifyContent: "center", minWidth: "0" }}>
                <input value={v.docName ?? ''} onChange={v.onDocName} style={{ width: "min(320px, 100%)", height: "32px", border: "1px solid transparent", background: "transparent", borderRadius: "7px", textAlign: "center", fontSize: "14px", fontWeight: "600", outline: "none" }} className="pw-h5" />
              </div>
              <div style={{ display: "flex", alignItems: "center", gap: "2px", background: "#F1EEE9", borderRadius: "8px", padding: "2px" }}>
                <button onClick={v.zoomOut} style={{ width: "28px", height: "28px", border: "none", background: "transparent", borderRadius: "6px", cursor: "pointer", fontSize: "16px", color: "#24211D" }} className="pw-h6">
                  −
                </button>
                <button onClick={v.zoomFit} title="Fit" style={{ minWidth: "52px", height: "28px", border: "none", background: "transparent", borderRadius: "6px", cursor: "pointer", fontSize: "12px", fontFamily: "'IBM Plex Mono', monospace", color: "#24211D" }} className="pw-h6">
                  {v.zoomLabel}
                </button>
                <button onClick={v.zoomIn} style={{ width: "28px", height: "28px", border: "none", background: "transparent", borderRadius: "6px", cursor: "pointer", fontSize: "16px", color: "#24211D" }} className="pw-h6">
                  +
                </button>
              </div>
              <button onClick={v.saveProject} title="Save .pinwheel (⌘S)" style={{ height: "34px", padding: "0 12px", borderRadius: "8px", border: "1px solid #E0DBD2", background: "#FFFFFF", fontWeight: "600", fontSize: "14px", cursor: "pointer", color: "#24211D" }} className="pw-h1">
                Save
              </button>
              <button onClick={v.toggleExport} style={{ height: "34px", padding: "0 16px", borderRadius: "8px", border: "none", background: "#E8674A", color: "#FFFFFF", fontWeight: "700", fontSize: "14px", cursor: "pointer" }} className="pw-h7">
                Export
              </button>
              {v.menuOpen ? (
                <>
                  <div onClick={v.closeMenus} style={{ position: "fixed", inset: "0", zIndex: "30" }} />
                </>
              ) : null}
              {v.fileOpen ? (
                <>
                  <div style={{ position: "absolute", top: "46px", left: "120px", width: "260px", background: "#FFFFFF", border: "1px solid #E6E1D9", borderRadius: "12px", boxShadow: "0 12px 32px rgba(36,33,29,.14)", padding: "6px", zIndex: "31", display: "flex", flexDirection: "column" }}>
                    {toArray(v.fileItems).map((m, $index) => (
                      <Fragment key={$index}>
                        <button onClick={m.onClick} style={{ display: "flex", justifyContent: "space-between", alignItems: "center", height: "36px", padding: "0 10px", border: "none", background: "transparent", borderRadius: "8px", cursor: "pointer", fontSize: "14px", color: "#24211D", textAlign: "left" }} className="pw-h8">
                          <span>
                            {m.label}
                          </span>
                          <span style={{ fontSize: "12px", color: "#9A9389", fontFamily: "'IBM Plex Mono', monospace" }}>
                            {m.hint}
                          </span>
                        </button>
                      </Fragment>
                    ))}
                  </div>
                </>
              ) : null}
              {v.resizeOpen ? (
                <>
                  <div style={{ position: "absolute", top: "46px", left: "170px", width: "340px", maxHeight: "70vh", overflow: "auto", background: "#FFFFFF", border: "1px solid #E6E1D9", borderRadius: "12px", boxShadow: "0 12px 32px rgba(36,33,29,.14)", padding: "6px", zIndex: "31", display: "flex", flexDirection: "column" }}>
                    {v.canRelayout ? (
                      <>
                        <button onClick={v.toggleRelayout} style={{ display: "flex", gap: "10px", alignItems: "flex-start", padding: "10px", border: "none", background: "#F7F5F1", borderRadius: "8px", cursor: "pointer", textAlign: "left", marginBottom: "6px", color: "#24211D" }}>
                          <span style={sty(v.relayoutBox)} />
                          <span style={{ display: "flex", flexDirection: "column", gap: "2px" }}>
                            <span style={{ fontWeight: "700", fontSize: "13px" }}>
                              Re-layout from template
                            </span>
                            <span style={{ fontSize: "12px", color: "#6E675E" }}>
                              Rebuilds the design for the new size instead of scaling. Edits to this page are replaced.
                            </span>
                          </span>
                        </button>
                      </>
                    ) : null}
                    {toArray(v.resizeItems).map((r, $index) => (
                      <Fragment key={$index}>
                        <button onClick={r.onClick} style={sty(r.style)}>
                          <span>
                            {r.label}
                          </span>
                          <span style={{ fontSize: "12px", color: "#9A9389", fontFamily: "'IBM Plex Mono', monospace" }}>
                            {r.dims}
                          </span>
                        </button>
                      </Fragment>
                    ))}
                  </div>
                </>
              ) : null}
              {v.exportOpen ? (
                <>
                  <div style={{ position: "absolute", top: "46px", right: "12px", width: "300px", background: "#FFFFFF", border: "1px solid #E6E1D9", borderRadius: "12px", boxShadow: "0 12px 32px rgba(36,33,29,.14)", padding: "12px", zIndex: "31", display: "flex", flexDirection: "column", gap: "10px" }}>
                    <div style={{ fontSize: "12px", fontWeight: "700", letterSpacing: ".06em", textTransform: "uppercase", color: "#8A837A" }}>
                      Quality
                    </div>
                    <div style={{ display: "flex", gap: "4px", background: "#F1EEE9", padding: "3px", borderRadius: "8px" }}>
                      {toArray(v.scaleOpts).map((s, $index) => (
                        <Fragment key={$index}>
                          <button onClick={s.onClick} style={sty(s.style)}>
                            {s.label}
                          </button>
                        </Fragment>
                      ))}
                    </div>
                    <div style={{ display: "flex", flexDirection: "column", gap: "2px" }}>
                      {toArray(v.exportItems).map((x, $index) => (
                        <Fragment key={$index}>
                          <button onClick={x.onClick} style={{ display: "flex", flexDirection: "column", alignItems: "flex-start", gap: "1px", padding: "8px 10px", border: "none", background: "transparent", borderRadius: "8px", cursor: "pointer", textAlign: "left", color: "#24211D" }} className="pw-h8">
                            <span style={{ fontWeight: "700", fontSize: "14px" }}>
                              {x.label}
                            </span>
                            <span style={{ fontSize: "12px", color: "#6E675E" }}>
                              {x.hint}
                            </span>
                          </button>
                        </Fragment>
                      ))}
                    </div>
                  </div>
                </>
              ) : null}
            </div>
            <div style={{ flex: "1", display: "flex", minHeight: "0" }}>
              <nav style={{ width: "76px", flex: "none", background: "#FBFAF8", borderRight: "1px solid #E6E1D9", display: "flex", flexDirection: "column", alignItems: "center", padding: "8px 0", gap: "2px", overflowY: "auto" }}>
                {toArray(v.rail).map((r, $index) => (
                  <Fragment key={$index}>
                    <button onClick={r.onClick} style={sty(r.style)}>
                      <span style={{ fontSize: "19px", lineHeight: "1" }}>
                        {r.glyph}
                      </span>
                      <span style={{ fontSize: "11px", fontWeight: "600" }}>
                        {r.label}
                      </span>
                    </button>
                  </Fragment>
                ))}
              </nav>
              {v.panelOpen ? (
                <>
                  <aside style={{ width: "320px", flex: "none", background: "#FBFAF8", borderRight: "1px solid #E6E1D9", display: "flex", flexDirection: "column", minHeight: "0" }}>
                    <div style={{ height: "48px", flex: "none", display: "flex", alignItems: "center", justifyContent: "space-between", padding: "0 16px" }}>
                      <span style={{ fontWeight: "700", fontSize: "15px" }}>
                        {v.panelTitle}
                      </span>
                      <button onClick={v.closePanel} title="Close panel" style={{ width: "28px", height: "28px", border: "none", background: "transparent", borderRadius: "6px", cursor: "pointer", fontSize: "16px", color: "#6E675E" }} className="pw-h4">
                        ‹
                      </button>
                    </div>
                    <div style={{ flex: "1", overflowY: "auto", padding: "0 16px 24px", display: "flex", flexDirection: "column", gap: "16px" }}>
                      {v.pTemplates ? (
                        <>
                          <input value={v.tplQ ?? ''} onChange={v.onTplQ} placeholder="Search templates" style={{ height: "38px", border: "1px solid #E0DBD2", borderRadius: "9px", padding: "0 12px", fontSize: "14px", outline: "none", background: "#FFFFFF" }} />
                          <div style={{ display: "flex", gap: "4px", background: "#F1EEE9", padding: "3px", borderRadius: "8px" }}>
                            {toArray(v.tplScopes).map((s, $index) => (
                              <Fragment key={$index}>
                                <button onClick={s.onClick} style={sty(s.style)}>
                                  {s.label}
                                </button>
                              </Fragment>
                            ))}
                          </div>
                          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "14px 10px", alignItems: "start" }}>
                            {toArray(v.tplItems).map((t, $index) => (
                              <Fragment key={$index}>
                                <button onClick={t.onClick} title={t.title} style={{ display: "flex", flexDirection: "column", gap: "5px", padding: "0", border: "none", background: "none", cursor: "pointer", textAlign: "left", minWidth: "0" }}>
                                  <div style={{ width: "100%", display: "flex", justifyContent: "center", alignItems: "center", background: "#EAE7E1", borderRadius: "8px", overflow: "hidden", minHeight: "60px" }} className="pw-h9">
                                    {t.thumb}
                                  </div>
                                  <span style={{ fontSize: "12px", color: "#6E675E", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>
                                    {t.name}
                                  </span>
                                </button>
                              </Fragment>
                            ))}
                          </div>
                          {v.tplHasMore ? (
                            <>
                              <button onClick={v.tplMore} style={{ height: "36px", borderRadius: "8px", border: "1px solid #E0DBD2", background: "#FFFFFF", fontWeight: "600", cursor: "pointer", color: "#24211D" }}>
                                More templates
                              </button>
                            </>
                          ) : null}
                        </>
                      ) : null}
                      {v.pStyles ? (
                        <>
                          <button onClick={v.shuffleStyle} style={{ height: "40px", borderRadius: "9px", border: "none", background: "#24211D", color: "#FFFFFF", fontWeight: "700", cursor: "pointer", fontSize: "14px" }}>
                            Shuffle palette & fonts
                          </button>
                          <div style={{ fontSize: "12px", fontWeight: "700", letterSpacing: ".06em", textTransform: "uppercase", color: "#8A837A" }}>
                            Color palettes
                          </div>
                          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "8px" }}>
                            {toArray(v.palItems).map((p, $index) => (
                              <Fragment key={$index}>
                                <button onClick={p.onClick} style={sty(p.style)}>
                                  <div style={{ display: "flex", height: "26px", borderRadius: "6px", overflow: "hidden" }}>
                                    {toArray(p.sw).map((c, $index) => (
                                      <Fragment key={$index}>
                                        <div style={sty(c)} />
                                      </Fragment>
                                    ))}
                                  </div>
                                  <span style={{ fontSize: "12px", fontWeight: "600", color: "#24211D" }}>
                                    {p.name}
                                  </span>
                                </button>
                              </Fragment>
                            ))}
                          </div>
                          <div style={{ fontSize: "12px", fontWeight: "700", letterSpacing: ".06em", textTransform: "uppercase", color: "#8A837A" }}>
                            Type pairings
                          </div>
                          <div style={{ display: "flex", flexDirection: "column", gap: "6px" }}>
                            {toArray(v.pairItems).map((p, $index) => (
                              <Fragment key={$index}>
                                <button onClick={p.onClick} style={sty(p.style)}>
                                  <span style={sty(p.dStyle)}>
                                    {p.display}
                                  </span>
                                  <span style={sty(p.bStyle)}>
                                    {p.body}
                                  </span>
                                </button>
                              </Fragment>
                            ))}
                          </div>
                        </>
                      ) : null}
                      {v.pElements ? (
                        <>
                          <div style={{ fontSize: "12px", fontWeight: "700", letterSpacing: ".06em", textTransform: "uppercase", color: "#8A837A" }}>
                            Shapes
                          </div>
                          <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: "6px" }}>
                            {toArray(v.shapeItems).map((s, $index) => (
                              <Fragment key={$index}>
                                <button onClick={s.onClick} title={s.label} style={{ aspectRatio: "1", display: "flex", alignItems: "center", justifyContent: "center", border: "1px solid #EAE6DF", background: "#FFFFFF", borderRadius: "8px", cursor: "pointer", padding: "0" }} className="pw-h3">
                                  {s.thumb}
                                </button>
                              </Fragment>
                            ))}
                          </div>
                          <div style={{ fontSize: "12px", fontWeight: "700", letterSpacing: ".06em", textTransform: "uppercase", color: "#8A837A" }}>
                            Lines
                          </div>
                          <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "6px" }}>
                            {toArray(v.lineItems).map((s, $index) => (
                              <Fragment key={$index}>
                                <button onClick={s.onClick} title={s.label} style={{ height: "52px", display: "flex", alignItems: "center", justifyContent: "center", border: "1px solid #EAE6DF", background: "#FFFFFF", borderRadius: "8px", cursor: "pointer", padding: "0" }} className="pw-h3">
                                  {s.thumb}
                                </button>
                              </Fragment>
                            ))}
                          </div>
                          <div style={{ fontSize: "12px", fontWeight: "700", letterSpacing: ".06em", textTransform: "uppercase", color: "#8A837A" }}>
                            Image frames
                          </div>
                          <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: "6px" }}>
                            {toArray(v.frameItems).map((s, $index) => (
                              <Fragment key={$index}>
                                <button onClick={s.onClick} title={s.label} style={{ aspectRatio: "1", display: "flex", alignItems: "center", justifyContent: "center", border: "1px solid #EAE6DF", background: "#FFFFFF", borderRadius: "8px", cursor: "pointer", padding: "0" }} className="pw-h3">
                                  {s.thumb}
                                </button>
                              </Fragment>
                            ))}
                          </div>
                        </>
                      ) : null}
                      {v.pText ? (
                        <>
                          {toArray(v.textBtns).map((t, $index) => (
                            <Fragment key={$index}>
                              <button onClick={t.onClick} style={sty(t.style)}>
                                {t.label}
                              </button>
                            </Fragment>
                          ))}
                          <div style={{ fontSize: "12px", fontWeight: "700", letterSpacing: ".06em", textTransform: "uppercase", color: "#8A837A" }}>
                            Font combinations
                          </div>
                          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "6px" }}>
                            {toArray(v.comboItems).map((p, $index) => (
                              <Fragment key={$index}>
                                <button onClick={p.onClick} style={{ display: "flex", flexDirection: "column", gap: "3px", alignItems: "center", justifyContent: "center", padding: "12px 6px", border: "1px solid #EAE6DF", background: "#FFFFFF", borderRadius: "8px", cursor: "pointer", minHeight: "72px", color: "#24211D", overflow: "hidden" }} className="pw-h3">
                                  <span style={sty(p.dStyle)}>
                                    {p.display}
                                  </span>
                                  <span style={sty(p.bStyle)}>
                                    {p.body}
                                  </span>
                                </button>
                              </Fragment>
                            ))}
                          </div>
                        </>
                      ) : null}
                      {v.pUploads ? (
                        <>
                          <button onClick={v.uploadClick} style={{ height: "44px", borderRadius: "9px", border: "none", background: "#E8674A", color: "#FFFFFF", fontWeight: "700", cursor: "pointer", fontSize: "14px" }} className="pw-h7">
                            Upload images
                          </button>
                          <div style={{ fontSize: "13px", color: "#6E675E", lineHeight: "1.45" }}>
                            Drop images anywhere on the canvas, or paste from the clipboard. Drag a thumbnail onto an image frame to fill it. Everything stays on this device.
                          </div>
                          {v.noUploads ? (
                            <>
                              <div style={{ border: "1.5px dashed #D8D3CA", borderRadius: "12px", padding: "28px 16px", textAlign: "center", color: "#8A837A", fontSize: "13px" }}>
                                No uploads yet
                              </div>
                            </>
                          ) : null}
                          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "8px" }}>
                            {toArray(v.uploadItems).map((u, $index) => (
                              <Fragment key={$index}>
                                <button onClick={u.onClick} draggable="true" onDragStart={u.onDragStart} style={{ aspectRatio: "1", padding: "0", border: "1px solid #EAE6DF", borderRadius: "8px", overflow: "hidden", cursor: "grab", background: "#EAE7E1" }} className="pw-h9">
                                  <div style={sty(u.imgStyle)} />
                                </button>
                              </Fragment>
                            ))}
                          </div>
                        </>
                      ) : null}
                      {v.pData ? (
                        <>
                          <div style={{ fontSize: "12px", fontWeight: "700", letterSpacing: ".06em", textTransform: "uppercase", color: "#8A837A" }}>
                            Charts
                          </div>
                          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "8px" }}>
                            {toArray(v.chartItems).map((s, $index) => (
                              <Fragment key={$index}>
                                <button onClick={s.onClick} style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: "6px", padding: "12px 8px 10px", border: "1px solid #EAE6DF", background: "#FFFFFF", borderRadius: "8px", cursor: "pointer", color: "#24211D" }} className="pw-h3">
                                  {s.thumb}
                                  <span style={{ fontSize: "12px", fontWeight: "600" }}>
                                    {s.label}
                                  </span>
                                </button>
                              </Fragment>
                            ))}
                          </div>
                          <div style={{ fontSize: "12px", fontWeight: "700", letterSpacing: ".06em", textTransform: "uppercase", color: "#8A837A" }}>
                            Codes
                          </div>
                          <button onClick={v.addQR} style={{ display: "flex", alignItems: "center", gap: "12px", padding: "10px", border: "1px solid #EAE6DF", background: "#FFFFFF", borderRadius: "8px", cursor: "pointer", textAlign: "left", color: "#24211D" }} className="pw-h3">
                            {v.qrThumb}
                            <span style={{ display: "flex", flexDirection: "column" }}>
                              <span style={{ fontWeight: "700" }}>
                                QR code
                              </span>
                              <span style={{ fontSize: "12px", color: "#6E675E" }}>
                                Link to a site, menu or event
                              </span>
                            </span>
                          </button>
                        </>
                      ) : null}
                      {v.pBrand ? (
                        <>
                          <div style={{ fontSize: "13px", color: "#6E675E", lineHeight: "1.45" }}>
                            Your brand kit sets the defaults for new designs and can restyle any template in one click. Saved on this device.
                          </div>
                          <div style={{ fontSize: "12px", fontWeight: "700", letterSpacing: ".06em", textTransform: "uppercase", color: "#8A837A" }}>
                            Colors
                          </div>
                          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "8px" }}>
                            {toArray(v.brandColors).map((b, $index) => (
                              <Fragment key={$index}>
                                <label style={{ display: "flex", alignItems: "center", gap: "8px", padding: "8px", border: "1px solid #EAE6DF", background: "#FFFFFF", borderRadius: "8px", cursor: "pointer" }}>
                                  <input type="color" value={b.value ?? ''} onChange={b.onChange} style={{ width: "30px", height: "30px", border: "none", padding: "0", background: "none", cursor: "pointer" }} />
                                  <span style={{ display: "flex", flexDirection: "column" }}>
                                    <span style={{ fontSize: "13px", fontWeight: "600" }}>
                                      {b.label}
                                    </span>
                                    <span style={{ fontSize: "11px", color: "#8A837A", fontFamily: "'IBM Plex Mono', monospace" }}>
                                      {b.value}
                                    </span>
                                  </span>
                                </label>
                              </Fragment>
                            ))}
                          </div>
                          <div style={{ fontSize: "12px", fontWeight: "700", letterSpacing: ".06em", textTransform: "uppercase", color: "#8A837A" }}>
                            Fonts
                          </div>
                          {toArray(v.brandFonts).map((b, $index) => (
                            <Fragment key={$index}>
                              <label style={{ display: "flex", flexDirection: "column", gap: "4px" }}>
                                <span style={{ fontSize: "13px", fontWeight: "600" }}>
                                  {b.label}
                                </span>
                                {b.selectNode}
                              </label>
                            </Fragment>
                          ))}
                          <div style={{ fontSize: "12px", fontWeight: "700", letterSpacing: ".06em", textTransform: "uppercase", color: "#8A837A" }}>
                            Logo
                          </div>
                          <div style={{ display: "flex", gap: "8px", alignItems: "center" }}>
                            {v.hasLogo ? (
                              <>
                                <button onClick={v.addLogo} title="Add logo to page" style={{ width: "64px", height: "64px", border: "1px solid #EAE6DF", background: "#FFFFFF", borderRadius: "8px", padding: "6px", cursor: "pointer" }}>
                                  <div style={sty(v.logoStyle)} />
                                </button>
                              </>
                            ) : null}
                            <button onClick={v.uploadLogo} style={{ height: "36px", padding: "0 12px", borderRadius: "8px", border: "1px solid #E0DBD2", background: "#FFFFFF", fontWeight: "600", cursor: "pointer", color: "#24211D" }}>
                              {v.logoBtnLabel}
                            </button>
                          </div>
                          <button onClick={v.applyBrand} style={{ height: "42px", borderRadius: "9px", border: "none", background: "#E8674A", color: "#FFFFFF", fontWeight: "700", cursor: "pointer", fontSize: "14px" }} className="pw-h7">
                            Apply brand to this design
                          </button>
                        </>
                      ) : null}
                      {v.pLayers ? (
                        <>
                          {v.noLayers ? (
                            <>
                              <div style={{ color: "#8A837A", fontSize: "13px" }}>
                                This page is empty.
                              </div>
                            </>
                          ) : null}
                          <div style={{ display: "flex", flexDirection: "column", gap: "3px" }}>
                            {toArray(v.layerItems).map((l, $index) => (
                              <Fragment key={$index}>
                                <div style={sty(l.style)}>
                                  <button onClick={l.onClick} style={{ flex: "1", minWidth: "0", display: "flex", flexDirection: "column", alignItems: "flex-start", border: "none", background: "transparent", cursor: "pointer", padding: "6px 4px", textAlign: "left", color: "#24211D" }}>
                                    <span style={{ fontSize: "13px", fontWeight: "600", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis", maxWidth: "100%" }}>
                                      {l.label}
                                    </span>
                                    <span style={{ fontSize: "11px", color: "#8A837A" }}>
                                      {l.meta}
                                    </span>
                                  </button>
                                  <button onClick={l.onUp} title="Bring forward" style={{ width: "24px", height: "24px", border: "none", background: "transparent", borderRadius: "5px", cursor: "pointer", color: "#6E675E" }} className="pw-h4">
                                    ↑
                                  </button>
                                  <button onClick={l.onDown} title="Send backward" style={{ width: "24px", height: "24px", border: "none", background: "transparent", borderRadius: "5px", cursor: "pointer", color: "#6E675E" }} className="pw-h4">
                                    ↓
                                  </button>
                                  <button onClick={l.onEye} title="Show / hide" style={sty(l.eyeStyle)}>
                                    {l.eye}
                                  </button>
                                  <button onClick={l.onLock} title="Lock / unlock" style={sty(l.lockStyle)}>
                                    {l.lock}
                                  </button>
                                </div>
                              </Fragment>
                            ))}
                          </div>
                        </>
                      ) : null}
                    </div>
                  </aside>
                </>
              ) : null}
              <div ref={v.setCanvasRef} onPointerDown={v.onCanvasDown} onDrop={v.onCanvasDrop} onDragOver={v.onCanvasDragOver} style={{ flex: "1", minWidth: "0", overflow: "auto", background: "#EAE7E1", position: "relative", userSelect: "none" }}>
                <div style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: "28px", padding: "36px 48px 64px", minWidth: "max-content" }}>
                  {toArray(v.pages).map((p, $index) => (
                    <Fragment key={$index}>
                      <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
                        <div style={{ display: "flex", alignItems: "center", gap: "4px", height: "26px" }}>
                          <button onClick={p.onFocus} style={sty(p.labelStyle)}>
                            {p.label}
                          </button>
                          <div style={{ flex: "1" }} />
                          <button onClick={p.onUp} title="Move page up" style={{ width: "26px", height: "26px", border: "none", background: "transparent", borderRadius: "6px", cursor: "pointer", color: "#6E675E" }} className="pw-h10">
                            ↑
                          </button>
                          <button onClick={p.onDown} title="Move page down" style={{ width: "26px", height: "26px", border: "none", background: "transparent", borderRadius: "6px", cursor: "pointer", color: "#6E675E" }} className="pw-h10">
                            ↓
                          </button>
                          <button onClick={p.onDup} title="Duplicate page" style={{ width: "26px", height: "26px", border: "none", background: "transparent", borderRadius: "6px", cursor: "pointer", color: "#6E675E" }} className="pw-h10">
                            ⧉
                          </button>
                          <button onClick={p.onDel} title="Delete page" style={{ width: "26px", height: "26px", border: "none", background: "transparent", borderRadius: "6px", cursor: "pointer", color: "#6E675E" }} className="pw-h10">
                            ✕
                          </button>
                          <button onClick={p.onAdd} title="Add page after" style={{ width: "26px", height: "26px", border: "none", background: "transparent", borderRadius: "6px", cursor: "pointer", color: "#6E675E", fontSize: "16px" }} className="pw-h10">
                            +
                          </button>
                        </div>
                        <div style={sty(p.wrapStyle)}>
                          <div style={sty(p.stageStyle)}>
                            {p.node}
                          </div>
                          {p.hasHover ? (
                            <>
                              <div style={sty(p.hoverStyle)} />
                            </>
                          ) : null}
                          {toArray(p.multi).map((mb, $index) => (
                            <Fragment key={$index}>
                              <div style={sty(mb)} />
                            </Fragment>
                          ))}
                          {p.hasSel ? (
                            <>
                              <div style={sty(p.selStyle)}>
                                {toArray(p.handles).map((hd, $index) => (
                                  <Fragment key={$index}>
                                    <div onPointerDown={hd.onDown} style={sty(hd.style)} />
                                  </Fragment>
                                ))}
                                {p.showRot ? (
                                  <>
                                    <div onPointerDown={p.onRot} title="Rotate" style={{ position: "absolute", left: "calc(50% - 11px)", top: "calc(100% + 14px)", width: "22px", height: "22px", borderRadius: "50%", background: "#FFFFFF", border: "1.5px solid #E8674A", pointerEvents: "auto", cursor: "grab", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "13px", color: "#E8674A", boxShadow: "0 1px 3px rgba(0,0,0,.15)" }}>
                                      ↻
                                    </div>
                                  </>
                                ) : null}
                                {p.showInfo ? (
                                  <>
                                    <div style={{ position: "absolute", left: "50%", bottom: "calc(100% + 8px)", transform: "translateX(-50%)", background: "#24211D", color: "#FFFFFF", fontSize: "11px", fontFamily: "'IBM Plex Mono', monospace", padding: "3px 7px", borderRadius: "5px", whiteSpace: "nowrap" }}>
                                      {p.info}
                                    </div>
                                  </>
                                ) : null}
                              </div>
                            </>
                          ) : null}
                          {toArray(p.guides).map((g, $index) => (
                            <Fragment key={$index}>
                              <div style={sty(g)} />
                            </Fragment>
                          ))}
                          {p.hasMarquee ? (
                            <>
                              <div style={sty(p.marqueeStyle)} />
                            </>
                          ) : null}
                        </div>
                      </div>
                    </Fragment>
                  ))}
                  <button onClick={v.addPageEnd} style={sty(v.addPageStyle)}>
                    + Add page
                  </button>
                </div>
              </div>
              <aside style={{ width: "292px", flex: "none", background: "#FBFAF8", borderLeft: "1px solid #E6E1D9", display: "flex", flexDirection: "column", minHeight: "0" }}>
                <div style={{ height: "48px", flex: "none", display: "flex", alignItems: "center", padding: "0 16px", borderBottom: "1px solid #EEEAE3" }}>
                  <span style={{ fontWeight: "700", fontSize: "15px" }}>
                    {v.propsTitle}
                  </span>
                </div>
                <div style={{ flex: "1", overflowY: "auto", display: "flex", flexDirection: "column" }}>
                  {toArray(v.sections).map((sec, $index) => (
                    <Fragment key={$index}>
                      <div style={{ padding: "14px 16px 16px", borderBottom: "1px solid #EEEAE3", display: "flex", flexDirection: "column", gap: "12px" }}>
                        <div style={{ fontSize: "12px", fontWeight: "700", letterSpacing: ".06em", textTransform: "uppercase", color: "#8A837A" }}>
                          {sec.title}
                        </div>
                        {toArray(sec.controls).map((c, $index) => (
                          <Fragment key={$index}>
                            <div style={{ display: "flex", flexDirection: "column", gap: "6px" }}>
                              {c.hasLabel ? (
                                <>
                                  <div style={{ display: "flex", justifyContent: "space-between", fontSize: "13px" }}>
                                    <span style={{ fontWeight: "600" }}>
                                      {c.label}
                                    </span>
                                    <span style={{ color: "#8A837A", fontFamily: "'IBM Plex Mono', monospace", fontSize: "12px" }}>
                                      {c.display}
                                    </span>
                                  </div>
                                </>
                              ) : null}
                              {c.isSlider ? (
                                <>
                                  <input type="range" min={c.min} max={c.max} step={c.step} value={c.value ?? ''} onChange={c.onChange} />
                                </>
                              ) : null}
                              {c.isNums ? (
                                <>
                                  <div style={sty(c.gridStyle)}>
                                    {toArray(c.items).map((n, $index) => (
                                      <Fragment key={$index}>
                                        <label style={{ display: "flex", alignItems: "center", gap: "4px", height: "32px", border: "1px solid #E0DBD2", borderRadius: "7px", background: "#FFFFFF", padding: "0 6px" }}>
                                          <span style={{ fontSize: "11px", color: "#9A9389", fontWeight: "700", width: "12px" }}>
                                            {n.label}
                                          </span>
                                          <input type="number" value={n.value ?? ''} step={n.step} onChange={n.onChange} style={{ flex: "1", minWidth: "0", border: "none", outline: "none", fontSize: "13px", fontFamily: "'IBM Plex Mono', monospace", background: "transparent" }} />
                                        </label>
                                      </Fragment>
                                    ))}
                                  </div>
                                </>
                              ) : null}
                              {c.isColor ? (
                                <>
                                  <div style={{ display: "flex", flexWrap: "wrap", gap: "6px", alignItems: "center" }}>
                                    {toArray(c.swatches).map((s, $index) => (
                                      <Fragment key={$index}>
                                        <button onClick={s.onClick} title={s.title} style={sty(s.style)} />
                                      </Fragment>
                                    ))}
                                    <label title="Custom color" style={{ width: "26px", height: "26px", borderRadius: "7px", border: "1px dashed #BDB6AB", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", position: "relative", overflow: "hidden", fontSize: "14px", color: "#6E675E" }}>
                                      + 
                                      <input type="color" value={c.hex ?? ''} onChange={c.onPick} style={{ position: "absolute", inset: "0", opacity: "0", cursor: "pointer" }} />
                                    </label>
                                  </div>
                                </>
                              ) : null}
                              {c.isSelect ? (
                                <>
                                  {c.selectNode}
                                </>
                              ) : null}
                              {c.isSeg ? (
                                <>
                                  <div style={{ display: "flex", flexWrap: "wrap", gap: "3px", background: "#F1EEE9", padding: "3px", borderRadius: "8px" }}>
                                    {toArray(c.opts).map((o, $index) => (
                                      <Fragment key={$index}>
                                        <button onClick={o.onClick} title={o.title} style={sty(o.style)}>
                                          {o.label}
                                        </button>
                                      </Fragment>
                                    ))}
                                  </div>
                                </>
                              ) : null}
                              {c.isText ? (
                                <>
                                  <input value={c.value ?? ''} onChange={c.onChange} style={{ height: "34px", border: "1px solid #E0DBD2", borderRadius: "7px", padding: "0 10px", fontSize: "13px", outline: "none", background: "#FFFFFF" }} />
                                </>
                              ) : null}
                              {c.isArea ? (
                                <>
                                  <textarea value={c.value ?? ''} onChange={c.onChange} rows="5" style={{ border: "1px solid #E0DBD2", borderRadius: "7px", padding: "8px 10px", fontSize: "13px", outline: "none", background: "#FFFFFF", fontFamily: "'IBM Plex Mono', monospace", resize: "vertical" }} />
                                </>
                              ) : null}
                              {c.isBtns ? (
                                <>
                                  <div style={{ display: "flex", flexWrap: "wrap", gap: "6px" }}>
                                    {toArray(c.items).map((b, $index) => (
                                      <Fragment key={$index}>
                                        <button onClick={b.onClick} title={b.title} style={sty(b.style)}>
                                          {b.label}
                                        </button>
                                      </Fragment>
                                    ))}
                                  </div>
                                </>
                              ) : null}
                              {c.isNote ? (
                                <>
                                  <div style={{ fontSize: "13px", lineHeight: "1.45", color: "#6E675E", textWrap: "pretty" }}>
                                    {c.text}
                                  </div>
                                </>
                              ) : null}
                            </div>
                          </Fragment>
                        ))}
                      </div>
                    </Fragment>
                  ))}
                </div>
              </aside>
            </div>
          </div>
        </>
      ) : null}
      <input type="file" ref={v.setImgInput} onChange={v.onImageFile} accept="image/*" multiple="multiple" style={{ display: "none" }} />
      <input type="file" ref={v.setFileInput} onChange={v.onProjectFile} accept=".pinwheel,.zip" style={{ display: "none" }} />
      <input type="file" ref={v.setLogoInput} onChange={v.onLogoFile} accept="image/*" style={{ display: "none" }} />
      {v.hasBusy ? (
        <>
          <div style={{ position: "fixed", inset: "0", background: "rgba(36,33,29,.28)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: "100" }}>
            <div style={{ background: "#FFFFFF", borderRadius: "14px", padding: "20px 26px", boxShadow: "0 20px 50px rgba(0,0,0,.2)", display: "flex", alignItems: "center", gap: "14px", fontSize: "15px", fontWeight: "600", maxWidth: "420px" }}>
              <div style={{ display: "grid", gridTemplateColumns: "9px 9px", gap: "2px", flex: "none" }}>
                <div style={{ width: "9px", height: "9px", background: "#E8674A", borderRadius: "9px 0 0 0" }} />
                <div style={{ width: "9px", height: "9px", background: "#24211D", borderRadius: "0 9px 0 0" }} />
                <div style={{ width: "9px", height: "9px", background: "#24211D", borderRadius: "0 0 0 9px" }} />
                <div style={{ width: "9px", height: "9px", background: "#E8674A", borderRadius: "0 0 9px 0" }} />
              </div>
              <span>
                {v.busyText}
              </span>
            </div>
          </div>
        </>
      ) : null}
      {v.hasToast ? (
        <>
          <div style={{ position: "fixed", left: "50%", bottom: "28px", transform: "translateX(-50%)", background: "#24211D", color: "#FFFFFF", padding: "10px 18px", borderRadius: "10px", fontSize: "14px", fontWeight: "600", zIndex: "101", boxShadow: "0 10px 30px rgba(0,0,0,.2)" }}>
            {v.toastText}
          </div>
        </>
      ) : null}
    </div>
    </>
  );
}
